# -*- coding: utf-8 -*-
"""Despliegue_Pantalones_con_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174vU98nkdd7yijyK-MM7AH7I7Y6d8kcN

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""



#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import pickle

# Cargar forecaster y data
with open("modelo-TimeSeries.pkl", "rb") as file:
    forecaster_cargado, data_cargada = pickle.load(file)

import streamlit as st


# ========================
# Cargar modelo entrenado
# ========================
with open("modelo-TimeSeries.pkl", "rb") as file:
    forecaster_cargado, data_cargada = pickle.load(file)

# ========================
# Interfaz de la aplicación
# ========================
st.title("📈 Estimación de ventas mensuales de pantalón - STOP JEANS")

st.markdown("Esta aplicación permite estimar la **Cantidad** de ventas futuras.")

# ========================
# Inputs del usuario
# ========================

# Selección de número de periodos a predecir
n_periodos = st.slider(
    "Selecciona cuántos meses deseas pronosticar:",
    min_value=1, max_value=24, value=6
)

# Botón de predicción
if st.button("Generar pronóstico"):
    # ========================
    # Generar predicciones
    # ========================
    y_pred = forecaster_cargado.predict(steps=n_periodos)

    # ========================
    # Mostrar resultados
    # ========================
    resultado = pd.DataFrame({
        "Fecha": y_pred.index,
        "Pronostico_Cantidad": y_pred.values
    })

    st.subheader("📊 Resultados del pronóstico")
    st.dataframe(resultado)

    # ========================
    # Graficar resultados
    # ========================
    st.line_chart(resultado.set_index("Fecha"))

#Cargamos los datos futuros
#data_preparada = pd.read_excel("pronostico_ventas.xlsx")
#data_preparada.head()
#data_preparada.drop(columns=['Cantidad'], inplace=True)
#data_preparada.head()

#n_periodos = len(data_preparada)   # cantidad de filas en tu Excel de fechas futuras
Y_pred = forecaster_cargado.predict(steps=n_periodos)

# Mostrar resultados
print(Y_pred)

#data_preparada = data_preparada.set_index('fecha')
data_preparada['Prediccion'] = Y_pred.round(0).astype(int)
data_preparada.head()

#Predicciones finales
data_preparada
